"use client";
import { useState } from "react";
import { Activity, Droplets, Lightbulb, Radio, Thermometer, Wifi } from "lucide-react";
import { useDevice } from "@/context/device-context";
import { useApiResource } from "@/hooks/use-api-resource";
import { dashboardService } from "@/services/dashboard.service";
import { formatNumber, relativeTime } from "@/lib/formatters";
import { rssiQuality } from "@/lib/utils";
import type { ChartRange } from "@/types";
import { SensorCard } from "@/components/dashboard/sensor-card";
import { EnvironmentChart, LightChart } from "@/components/dashboard/charts";
import { Badge, Card, CardContent, CardHeader } from "@/components/ui";
import { EmptyState, ErrorState, PageSkeleton } from "@/components/common/states";

const ranges: { label: string; value: ChartRange }[] = [{ label: "1 Hour", value: "1h" }, { label: "24 Hours", value: "24h" }, { label: "7 Days", value: "7d" }, { label: "30 Days", value: "30d" }];
export default function DashboardPage() {
  const { selectedDeviceId } = useDevice(); const [range, setRange] = useState<ChartRange>("24h");
  const resource = useApiResource((signal) => dashboardService.get(selectedDeviceId, range, signal), [selectedDeviceId, range]);
  if (resource.loading && !resource.data) return <PageSkeleton/>;
  if (resource.error && !resource.data) return <ErrorState message={resource.error} retry={resource.retry}/>;
  const data = resource.data; if (!data) return <EmptyState title="No sensor readings yet."/>;
  const { latestReading: r, settings: s, device } = data;
  const temperatureHigh = r.temperatureC > s.highTemperature;
  const humidityNormal = r.humidityPercent >= s.lowHumidity && r.humidityPercent <= s.highHumidity;
  const lightStatus = r.lightValue < s.lowLight ? "Dark" : r.lightValue > s.highLight ? "Bright" : "Normal";
  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-semibold tracking-tight">Environment Overview</h2><p className="mt-1 text-sm text-slate-500">Real-time monitoring and environmental insights</p></div><div className="flex flex-wrap gap-2">{ranges.map((item) => <button key={item.value} onClick={() => setRange(item.value)} className={`rounded-lg px-3 py-2 text-xs font-medium ${range === item.value ? "bg-blue-600 text-white" : "border border-slate-200 bg-white text-slate-600"}`}>{item.label}</button>)}</div></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><SensorCard title="Temperature" value={formatNumber(r.temperatureC)} unit="°C" status={temperatureHigh ? "High" : "Normal"} detail={`High ${s.highTemperature} °C`} icon={Thermometer}/><SensorCard title="Humidity" value={formatNumber(r.humidityPercent, 0)} unit="%" status={humidityNormal ? "Normal" : "Attention"} detail={`${s.lowHumidity}–${s.highHumidity}%`} icon={Droplets} color="cyan"/><SensorCard title="Light Level" value={formatNumber(r.lightValue, 0)} status={lightStatus} detail="Raw reading" icon={Lightbulb} color="amber"/><SensorCard title="Motion" value={r.motionDetected ? "Detected" : "No Motion"} status={`${data.motionEventsToday} events today`} icon={Radio} color="violet"/></div>
  <Card><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className={`rounded-xl p-3 ${data.environmentStatus === "normal" ? "bg-emerald-50 text-emerald-600" : "bg-amber-50 text-amber-600"}`}><Activity/></span><div><p className="text-sm text-slate-500">Overall Environment</p><p className="font-semibold">Environment Status: {data.environmentStatus === "normal" ? "Normal" : "Attention Required"}</p></div></div><Badge className={data.environmentStatus === "normal" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}>{data.alerts.filter((a) => a.status === "active").length} active alerts</Badge></CardContent></Card>
  {data.chartReadings.length ? <div className="grid gap-6 xl:grid-cols-2"><EnvironmentChart data={data.chartReadings} longRange={range === "7d" || range === "30d"}/><LightChart data={data.chartReadings} longRange={range === "7d" || range === "30d"}/></div> : <EmptyState title="No historical readings yet."/>}
  <div className="grid gap-6 xl:grid-cols-3"><Card><CardHeader><h2 className="font-semibold">Device Status</h2></CardHeader><CardContent className="space-y-4"><Info label="Device" value={device.name || device.id}/><Info label="Status" value={device.status === "online" ? "Online" : "Offline"}/><Info label="Location" value={device.location}/><Info label="Last Seen" value={relativeTime(device.lastSeen)}/><Info label="Wi-Fi Signal" value={`${device.wifiRssi} dBm · ${rssiQuality(device.wifiRssi)}`} icon={<Wifi className="h-4 w-4 text-blue-600"/>}/></CardContent></Card><Card><CardHeader><h2 className="font-semibold">Active Alerts</h2></CardHeader><CardContent>{data.alerts.filter((a) => a.status === "active").length ? <div className="space-y-3">{data.alerts.filter((a) => a.status === "active").slice(0,5).map((a) => <div key={a.id} className="rounded-lg border border-amber-100 bg-amber-50/60 p-3"><p className="text-sm font-medium">{a.title}</p><p className="mt-1 text-xs text-slate-500">{a.value}{a.unit ? ` ${a.unit}` : ""} · {relativeTime(a.triggeredAt)}</p></div>)}</div> : <p className="py-8 text-center text-sm text-slate-500">No active alerts.</p>}</CardContent></Card><Card><CardHeader><h2 className="font-semibold">Recent Activity</h2></CardHeader><CardContent>{data.alerts.length || data.recentReadings.some((x) => x.motionDetected) ? <div className="space-y-4">{[...data.alerts.slice(0,3).map((a) => ({ id: a.id, text: a.title, at: a.triggeredAt })), ...data.recentReadings.filter((x) => x.motionDetected).slice(0,2).map((x) => ({ id: x.id, text: "Motion detected", at: x.timestamp }))].sort((a,b) => Date.parse(b.at)-Date.parse(a.at)).slice(0,5).map((item) => <div key={item.id} className="flex gap-3"><span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-blue-500"/><div><p className="text-sm font-medium">{item.text}</p><p className="text-xs text-slate-500">{relativeTime(item.at)}</p></div></div>)}</div> : <p className="py-8 text-center text-sm text-slate-500">No recent activity.</p>}</CardContent></Card></div></div>;
}
function Info({ label, value, icon }: { label: string; value: string; icon?: React.ReactNode }) { return <div className="flex items-center justify-between gap-3 border-b border-slate-100 pb-3 last:border-0"><span className="text-sm text-slate-500">{label}</span><span className="flex items-center gap-2 text-right text-sm font-medium">{icon}{value}</span></div>; }
