"use client";
import { useState } from "react";
import { Droplets, Lightbulb, Radio, Thermometer } from "lucide-react";
import { useDevice } from "@/context/device-context";
import { useApiResource } from "@/hooks/use-api-resource";
import { analyticsService } from "@/services/analytics.service";
import type { AnalyticsRange, MetricStats } from "@/types";
import { Card, CardContent } from "@/components/ui";
import { EnvironmentChart, LightChart } from "@/components/dashboard/charts";
import { EmptyState, ErrorState, PageSkeleton } from "@/components/common/states";
import { formatNumber } from "@/lib/formatters";

const ranges: { label: string; value: AnalyticsRange }[] = [{ label: "24 Hours", value: "24h" }, { label: "7 Days", value: "7d" }, { label: "30 Days", value: "30d" }];
export default function AnalyticsPage() { const { selectedDeviceId } = useDevice(); const [range,setRange] = useState<AnalyticsRange>("24h"); const resource = useApiResource((signal) => analyticsService.get(selectedDeviceId,range,signal),[selectedDeviceId,range]); if(resource.loading&&!resource.data)return <PageSkeleton/>; if(resource.error&&!resource.data)return <ErrorState message={resource.error} retry={resource.retry}/>; const data=resource.data; if(!data)return <EmptyState title="No analytics available yet."/>; return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-semibold">Environmental Analytics</h2><p className="mt-1 text-sm text-slate-500">Aggregated measurements and long-term trends</p></div><div className="flex gap-2">{ranges.map((r)=><button key={r.value} onClick={()=>setRange(r.value)} className={`rounded-lg px-3 py-2 text-sm font-medium ${range===r.value?"bg-blue-600 text-white":"border bg-white text-slate-600"}`}>{r.label}</button>)}</div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Stats title="Temperature" stats={data.temperature} unit="°C" icon={<Thermometer/>}/><Stats title="Humidity" stats={data.humidity} unit="%" icon={<Droplets/>}/><Stats title="Light Level" stats={data.light} unit="" icon={<Lightbulb/>}/><Card><CardContent className="p-5"><div className="flex items-center justify-between"><p className="font-semibold">Motion</p><span className="text-violet-600"><Radio/></span></div><p className="mt-6 text-3xl font-semibold">{data.totalMotionEvents}</p><p className="mt-1 text-sm text-slate-500">Total Motion Events</p></CardContent></Card></div>{data.readings.length?<div className="grid gap-6 xl:grid-cols-2"><EnvironmentChart data={data.readings} longRange={range!=="24h"}/><LightChart data={data.readings} longRange={range!=="24h"}/></div>:<EmptyState title="No sensor readings yet."/>}</div>; }
function Stats({title,stats,unit,icon}:{title:string;stats:MetricStats;unit:string;icon:React.ReactNode}){return <Card><CardContent className="p-5"><div className="flex items-center justify-between"><p className="font-semibold">{title}</p><span className="text-blue-600">{icon}</span></div><div className="mt-5 grid grid-cols-3 gap-2"><Stat label="Average" value={stats.average} unit={unit}/><Stat label="Minimum" value={stats.minimum} unit={unit}/><Stat label="Maximum" value={stats.maximum} unit={unit}/></div></CardContent></Card>}
function Stat({label,value,unit}:{label:string;value:number;unit:string}){return <div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-lg font-semibold">{formatNumber(value)}<span className="text-xs text-slate-500"> {unit}</span></p></div>}
