"use client";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Card, CardContent, CardHeader } from "@/components/ui";
import { chartTime } from "@/lib/formatters";
import type { ChartReading } from "@/types";

const tooltipStyle = { borderRadius: 10, border: "1px solid #e2e8f0", boxShadow: "0 4px 15px rgba(15,23,42,.08)" };
export function EnvironmentChart({ data, longRange = false }: { data: ChartReading[]; longRange?: boolean }) { return <Card><CardHeader><h2 className="font-semibold">Temperature & Humidity</h2><p className="text-sm text-slate-500">Environmental trends over time</p></CardHeader><CardContent><div className="h-72 w-full"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ left: -15, right: 10 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="timestamp" tickFormatter={(v) => chartTime(v, longRange)} tick={{ fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis yAxisId="temperature" tick={{ fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis yAxisId="humidity" orientation="right" tick={{ fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip labelFormatter={(v) => chartTime(String(v), longRange)} contentStyle={tooltipStyle}/><Line yAxisId="temperature" type="monotone" dataKey="temperatureC" name="Temperature °C" stroke="#2563eb" strokeWidth={2} dot={false}/><Line yAxisId="humidity" type="monotone" dataKey="humidityPercent" name="Humidity %" stroke="#0891b2" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></CardContent></Card>; }
export function LightChart({ data, longRange = false }: { data: ChartReading[]; longRange?: boolean }) { return <Card><CardHeader><h2 className="font-semibold">Light Level</h2><p className="text-sm text-slate-500">Raw sensor readings, not lux</p></CardHeader><CardContent><div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ left: -15, right: 10 }}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0"/><XAxis dataKey="timestamp" tickFormatter={(v) => chartTime(v, longRange)} tick={{ fontSize: 11 }} axisLine={false} tickLine={false}/><YAxis tick={{ fontSize: 11 }} axisLine={false} tickLine={false}/><Tooltip labelFormatter={(v) => chartTime(String(v), longRange)} contentStyle={tooltipStyle}/><Line type="monotone" dataKey="lightValue" name="Light Level" stroke="#d97706" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div></CardContent></Card>; }
