"use client";
import { useState } from "react";
import { CheckCircle2 } from "lucide-react";
import { toast } from "sonner";
import { useApiResource } from "@/hooks/use-api-resource";
import { alertsService } from "@/services/alerts.service";
import { relativeTime } from "@/lib/formatters";
import type { AlertStatus } from "@/types";
import { Badge, Button, Card } from "@/components/ui";
import { EmptyState, ErrorState, PageSkeleton } from "@/components/common/states";

type Filter = "all" | AlertStatus;
export default function AlertsPage(){const[filter,setFilter]=useState<Filter>("all");const[resolving,setResolving]=useState<string|null>(null);const resource=useApiResource((signal)=>alertsService.list(filter==="all"?{}:{status:filter},signal),[filter]);async function resolve(id:string){if(!window.confirm("Resolve this alert?"))return;setResolving(id);try{await alertsService.resolve(id);toast.success("Alert resolved");resource.retry();}catch(e){toast.error(e instanceof Error?e.message:"Unable to resolve alert.");}finally{setResolving(null)}}if(resource.loading&&!resource.data)return <PageSkeleton/>;if(resource.error&&!resource.data)return <ErrorState message={resource.error} retry={resource.retry}/>;const alerts=resource.data||[];return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-semibold">Environmental Alerts</h2><p className="mt-1 text-sm text-slate-500">Review and resolve monitoring exceptions</p></div><div className="flex gap-2">{(["all","active","resolved"] as Filter[]).map((x)=><button key={x} onClick={()=>setFilter(x)} className={`rounded-lg px-4 py-2 text-sm font-medium capitalize ${filter===x?"bg-blue-600 text-white":"border bg-white text-slate-600"}`}>{x}</button>)}</div></div>{alerts.length?<Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{["Alert","Device","Severity","Value","Triggered","Status","Action"].map((x)=><th key={x} className="px-5 py-4 font-medium">{x}</th>)}</tr></thead><tbody className="divide-y">{alerts.map((a)=><tr key={a.id} className="hover:bg-slate-50/60"><td className="px-5 py-4 font-medium">{a.title}</td><td className="px-5 py-4 text-slate-600">{a.deviceId}</td><td className="px-5 py-4"><Badge className={a.severity==="critical"?"bg-red-50 text-red-700":a.severity==="warning"?"bg-amber-50 text-amber-700":"bg-blue-50 text-blue-700"}>{a.severity}</Badge></td><td className="px-5 py-4">{a.value}{a.unit?` ${a.unit}`:""}</td><td className="px-5 py-4 text-slate-600">{relativeTime(a.triggeredAt)}</td><td className="px-5 py-4"><Badge className={a.status==="active"?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700"}>{a.status}</Badge></td><td className="px-5 py-4">{a.status==="active"?<Button disabled={resolving===a.id} onClick={()=>void resolve(a.id)} className="h-8 bg-white px-3 text-blue-700 ring-1 ring-blue-200 hover:bg-blue-50"><CheckCircle2 className="h-4 w-4"/>{resolving===a.id?"Resolving…":"Resolve"}</Button>:<span className="text-slate-400">Completed</span>}</td></tr>)}</tbody></table></div></Card>:<EmptyState title="No alerts found." description="No alerts match the selected filter."/>}</div>}
