"use client";
import { useState } from "react";
import { Info, Save } from "lucide-react";
import { toast } from "sonner";
import { useDevice } from "@/context/device-context";
import { useApiResource } from "@/hooks/use-api-resource";
import { settingsService } from "@/services/settings.service";
import { validateSettings, type SettingsErrors } from "@/lib/settings-validation";
import type { DeviceSettings } from "@/types";
import { Button, Card, CardContent, CardHeader, Input } from "@/components/ui";
import { ErrorState, PageSkeleton } from "@/components/common/states";

const fields: {key:keyof DeviceSettings;label:string;unit:string;group:string}[]=[{key:"highTemperature",label:"High Temperature",unit:"°C",group:"Temperature Thresholds"},{key:"lowTemperature",label:"Low Temperature",unit:"°C",group:"Temperature Thresholds"},{key:"highHumidity",label:"High Humidity",unit:"%",group:"Humidity Thresholds"},{key:"lowHumidity",label:"Low Humidity",unit:"%",group:"Humidity Thresholds"},{key:"lowLight",label:"Low Light",unit:"raw",group:"Light Thresholds"},{key:"highLight",label:"High Light",unit:"raw",group:"Light Thresholds"},{key:"samplingIntervalSeconds",label:"Sampling Interval",unit:"seconds",group:"Device Intervals"},{key:"publishIntervalSeconds",label:"Publish Interval",unit:"seconds",group:"Device Intervals"}];
export default function SettingsPage(){const{selectedDeviceId}=useDevice();const resource=useApiResource((signal)=>settingsService.get(selectedDeviceId,signal),[selectedDeviceId]);if(resource.loading)return <PageSkeleton/>;if(resource.error)return <ErrorState message={resource.error} retry={resource.retry}/>;if(!resource.data)return null;return <SettingsForm key={selectedDeviceId} deviceId={selectedDeviceId} initial={resource.data}/>}

function SettingsForm({deviceId,initial}:{deviceId:string;initial:DeviceSettings}){const[values,setValues]=useState(initial);const[errors,setErrors]=useState<SettingsErrors>({});const[saving,setSaving]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();const found=validateSettings(values);setErrors(found);if(Object.keys(found).length)return;setSaving(true);try{const result=await settingsService.update(deviceId,values);setValues(result);toast.success("Device settings saved and queued for transmission.");}catch(e){toast.error(e instanceof Error?e.message:"Unable to save device settings.");}finally{setSaving(false)}}const groups=[...new Set(fields.map((f)=>f.group))];return <div className="space-y-6"><div><h2 className="text-2xl font-semibold">Device Settings</h2><p className="mt-1 text-sm text-slate-500">Configure thresholds and telemetry intervals for {deviceId}</p></div><div className="flex gap-3 rounded-xl border border-blue-100 bg-blue-50 p-4 text-blue-900"><Info className="mt-0.5 h-5 w-5 shrink-0 text-blue-600"/><div><p className="font-medium">Server-managed device configuration</p><p className="mt-1 text-sm text-blue-800/80">Changes are stored by the server and transmitted to the selected ESP32 through MQTT.</p></div></div><form onSubmit={submit}><Card><CardHeader><h3 className="font-semibold">Monitoring Configuration</h3><p className="text-sm text-slate-500">All interval values are measured in seconds.</p></CardHeader><CardContent className="space-y-8">{groups.map((group)=><section key={group}><h4 className="mb-4 text-sm font-semibold text-slate-700">{group}</h4><div className="grid gap-5 sm:grid-cols-2">{fields.filter((f)=>f.group===group).map((f)=><label key={f.key} className="block"><span className="mb-2 block text-sm font-medium">{f.label}</span><div className="relative"><Input type="number" step={f.unit==="seconds"?1:"any"} value={values[f.key]} onChange={(e)=>{setValues({...values,[f.key]:Number(e.target.value)});setErrors({...errors,[f.key]:undefined})}} aria-invalid={Boolean(errors[f.key])}/><span className="absolute right-3 top-2.5 text-sm text-slate-400">{f.unit}</span></div>{errors[f.key]&&<span className="mt-1 block text-xs text-red-600">{errors[f.key]}</span>}</label>)}</div></section>)}<div className="flex justify-end border-t pt-5"><Button type="submit" disabled={saving}><Save className="h-4 w-4"/>{saving?"Saving…":"Save Settings"}</Button></div></CardContent></Card></form></div>}
